// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ggDHawEoHH6D08Sy8j_QRxi3L5klBxY',
    appId: '1:267226608096:android:ebf296583029ca4b7e7b85',
    messagingSenderId: '267226608096',
    projectId: 'authtest-30f09',
    storageBucket: 'authtest-30f09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfJZ4x1nc5dkCcL4e-i_C-omlOEm0d0vs',
    appId: '1:267226608096:ios:a10ec6fbd1a242cc7e7b85',
    messagingSenderId: '267226608096',
    projectId: 'authtest-30f09',
    storageBucket: 'authtest-30f09.firebasestorage.app',
    androidClientId:
        '267226608096-2g845igv5sqfeksm31ebih78jfhps51v.apps.googleusercontent.com',
    iosClientId:
        '267226608096-mi8tvp6etu77edfn9mlsagd65t2cf72f.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
